"""
Internationalization (i18n) for stanza.
Supports: EN (English), RU (Russian), KZ-C (Kazakh Cyrillic), KZ-L (Kazakh Latin)
"""
from __future__ import annotations
EN   = "en"
RU   = "ru"
KZ_C = "kz_c"
KZ_L = "kz_l"
_STRINGS: dict[str, dict[str, str]] = {
    "lang_prompt": {
        EN:   "Choose language",
        RU:   "Выбери язык",
        KZ_C: "Тілді таңда",
        KZ_L: "Tildi tanda",
    },
    "lang_en": {
        EN:   "English",
        RU:   "English",
        KZ_C: "English",
        KZ_L: "English",
    },
    "lang_ru": {
        EN:   "Русский",
        RU:   "Русский",
        KZ_C: "Русский",
        KZ_L: "Rusşa",
    },
    "lang_kz": {
        EN:   "Қазақша / Qazaqsha",
        RU:   "Қазақша / Qazaqsha",
        KZ_C: "Қазақша / Qazaqsha",
        KZ_L: "Qazaqsha / Қазақша",
    },
    "lang_kz_script_prompt": {
        EN:   "Choose Kazakh script",
        RU:   "Выбери письменность казахского",
        KZ_C: "Жазу түрін таңда",
        KZ_L: "Jazw türin tanda",
    },
    "lang_kz_cyrillic": {
        EN:   "Қазақша (Cyrillic)",
        RU:   "Қазақша (кириллица)",
        KZ_C: "Қазақша (кирилл)",
        KZ_L: "Qazaqsha (Kirill)",
    },
    "lang_kz_latin": {
        EN:   "Qazaqsha (Latin)",
        RU:   "Qazaqsha (латиница)",
        KZ_C: "Qazaqsha (латын)",
        KZ_L: "Qazaqsha (Latyn)",
    },
    "app_name": {
        EN:   "stanza",
        RU:   "stanza",
        KZ_C: "stanza",
        KZ_L: "stanza",
    },
    "app_subtitle": {
        EN:   "WhatsApp Chat Analyzer",
        RU:   "Анализатор чатов WhatsApp",
        KZ_C: "WhatsApp чат талдаушы",
        KZ_L: "WhatsApp şat taldawşy",
    },
    "version": {
        EN:   "v1.0",
        RU:   "v1.0",
        KZ_C: "v1.0",
        KZ_L: "v1.0",
    },
    "file_label": {
        EN:   "File",
        RU:   "Файл",
        KZ_C: "Файл",
        KZ_L: "Faıl",
    },
    "saving_label": {
        EN:   "Saving",
        RU:   "Сохранение",
        KZ_C: "Сақтау",
        KZ_L: "Saqtaw",
    },
    "saving_on": {
        EN:   "ON",
        RU:   "ВКЛ",
        KZ_C: "ҚОСУЛЫ",
        KZ_L: "QOSULY",
    },
    "saving_off": {
        EN:   "OFF",
        RU:   "ВЫКЛ",
        KZ_C: "ӨШІРУЛІ",
        KZ_L: "Öşirwli",
    },
    "results_arrow": {
        EN:   "results go to results.txt",
        RU:   "результаты → results.txt",
        KZ_C: "нәтижелер → results.txt",
        KZ_L: "nätijeler → results.txt",
    },
    "choose_action": {
        EN:   "Choose action",
        RU:   "Выбери действие",
        KZ_C: "Әрекет таңда",
        KZ_L: "Äreqet tanda",
    },
    "invalid_choice": {
        EN:   "Invalid choice. Try again.",
        RU:   "Неверный выбор. Попробуй снова.",
        KZ_C: "Қате таңдау. Қайталап көр.",
        KZ_L: "Qate tandaw. Qaıtalap kör.",
    },
    "press_enter": {
        EN:   "  Press Enter to return to menu...",
        RU:   "  Нажми Enter чтобы вернуться в меню...",
        KZ_C: "  Мәзірге оралу үшін Enter басыңыз...",
        KZ_L: "  Mäzirge oralw üşin Enter basınyz...",
    },
    "exit_msg": {
        EN:   "Goodbye.",
        RU:   "Выход.",
        KZ_C: "Шығу.",
        KZ_L: "Şyğw.",
    },
    "found_files_title": {
        EN:   "Found .txt files in folder",
        RU:   "Найденные .txt файлы в папке",
        KZ_C: "Қалтадан табылған .txt файлдар",
        KZ_L: "Qaltadan tabylğan .txt faıldar",
    },
    "file_col": {
        EN:   "File",
        RU:   "Файл",
        KZ_C: "Файл",
        KZ_L: "Faıl",
    },
    "size_col": {
        EN:   "Size",
        RU:   "Размер",
        KZ_C: "Көлем",
        KZ_L: "Kölem",
    },
    "file_picker_hint": {
        EN:   "Enter number, full path to another file, or Enter for chat.txt",
        RU:   "Введи номер, полный путь к другому файлу, или Enter для chat.txt",
        KZ_C: "Нөмірді, басқа файлдың жолын енгіз немесе chat.txt үшін Enter басыңыз",
        KZ_L: "Nömirdi, basqa faıldyń jolyn engiz nemese chat.txt üşin Enter basınyz",
    },
    "file_picker_no_files": {
        EN:   "No .txt files found. Enter path manually:",
        RU:   "В папке не найдены .txt файлы. Укажи путь вручную:",
        KZ_C: "Қалтада .txt файлдар жоқ. Жолды қолмен енгіз:",
        KZ_L: "Qaltada .txt faıldar joq. Joldy qolmen engiz:",
    },
    "file_prompt": {
        EN:   "Chat file",
        RU:   "Файл чата",
        KZ_C: "Чат файлы",
        KZ_L: "Şat faıly",
    },
    "file_path_prompt": {
        EN:   "Path to chat file",
        RU:   "Путь к файлу чата",
        KZ_C: "Чат файлының жолы",
        KZ_L: "Şat faılynyn joly",
    },
    "invalid_number": {
        EN:   "Invalid number.",
        RU:   "Неверный номер.",
        KZ_C: "Қате нөмір.",
        KZ_L: "Qate nömir.",
    },
    "file_not_found": {
        EN:   "File not found",
        RU:   "Файл не найден",
        KZ_C: "Файл табылмады",
        KZ_L: "Faıl tabylmady",
    },
    "no_file_selected": {
        EN:   "No file selected. Exiting.",
        RU:   "Файл не выбран. Выход.",
        KZ_C: "Файл таңдалмады. Шығу.",
        KZ_L: "Faıl tandalmady. Şyğw.",
    },
    "parsing": {
        EN:   "Parsing",
        RU:   "Парсинг",
        KZ_C: "Талдау",
        KZ_L: "Taldaw",
    },
    "loaded": {
        EN:   "Loaded {total} messages ({user} user, {system} system)",
        RU:   "Загружено {total} сообщений ({user} пользовательских, {system} системных)",
        KZ_C: "Жүктелді {total} хабар ({user} пайдаланушы, {system} жүйелік)",
        KZ_L: "Jükteldi {total} habar ({user} paıdalanwşy, {system} jüıelik)",
    },
    "loaded_label": {
        EN:   "Loaded",
        RU:   "Загружен",
        KZ_C: "Жүктелді",
        KZ_L: "Jükteldi",
    },
    "menu_summary":      { EN: "Chat overview",          RU: "Обзор чата",              KZ_C: "Чат шолу",              KZ_L: "Şat şolw"              },
    "menu_users":        { EN: "Top users",              RU: "Топ пользователей",       KZ_C: "Топ пайдаланушылар",    KZ_L: "Top paıdalanwşylar"    },
    "menu_activity":     { EN: "Activity over time",     RU: "Активность по времени",   KZ_C: "Уақыт бойынша белсенділік", KZ_L: "Waqyt boınşa belsendіlіk" },
    "menu_graph":        { EN: "Interaction graph",      RU: "Граф взаимодействий",     KZ_C: "Өзара әрекет графы",   KZ_L: "Özara äreqet grafy"    },
    "menu_topics":       { EN: "Topics & tech stack",    RU: "Темы и технологии",       KZ_C: "Тақырыптар мен технологиялар", KZ_L: "Taqyrypttar men texnologıalar" },
    "menu_media":        { EN: "Media files",            RU: "Медиафайлы",              KZ_C: "Медиафайлдар",          KZ_L: "Medıafaıldar"          },
    "menu_ghosts":       { EN: "Silent members",         RU: "Молчуны",                 KZ_C: "Үнсіздер",             KZ_L: "Ünsizder"              },
    "menu_penalties":    { EN: "Penalty events",         RU: "Штрафные баллы",          KZ_C: "Айыппұл оқиғалары",    KZ_L: "Aıyppwl oqığaları"     },
    "menu_all":          { EN: "Run all analyses",       RU: "Запустить всё",           KZ_C: "Барлығын іске қос",    KZ_L: "Barlığyn iske qos"     },
    "menu_digest":       { EN: "AI daily digest",        RU: "AI-дайджест по дням",     KZ_C: "AI күнделікті дайджест", KZ_L: "AI kündeligı daıjest" },
    "menu_save_toggle":  { EN: "Toggle saving to results.txt", RU: "Включить/выключить сохранение в results.txt", KZ_C: "results.txt-ке сақтауды қос/өшір", KZ_L: "results.txt-ke saqtawdy qos/öşir" },
    "menu_clear":        { EN: "Clear results.txt",      RU: "Очистить results.txt",    KZ_C: "results.txt тазарту",  KZ_L: "results.txt tazartw"   },
    "menu_change_file":  { EN: "Change chat file",       RU: "Сменить файл чата",       KZ_C: "Чат файлын ауыстыру", KZ_L: "Şat faılın awıstyrw"  },
    "menu_quit":         { EN: "Quit",                   RU: "Выход",                   KZ_C: "Шығу",                 KZ_L: "Şyğw"                  },
    "save_enabled": {
        EN:   "Saving to results.txt: enabled",
        RU:   "Сохранение в results.txt: включено",
        KZ_C: "results.txt-ке сақтау: қосулы",
        KZ_L: "results.txt-ke saqtaw: qosuly",
    },
    "save_disabled": {
        EN:   "Saving to results.txt: disabled",
        RU:   "Сохранение в results.txt: выключено",
        KZ_C: "results.txt-ке сақтау: өшірілген",
        KZ_L: "results.txt-ke saqtaw: öşirilgen",
    },
    "clear_confirm": {
        EN:   "Clear results.txt? This will delete all saved results",
        RU:   "Очистить results.txt? Это удалит все сохранённые результаты",
        KZ_C: "results.txt тазартылсын ба? Барлық сақталған нәтижелер жойылады",
        KZ_L: "results.txt tazartylsyn ba? Barlıq saqtalğan nätijeler joıylady",
    },
    "clear_done": {
        EN:   "results.txt cleared.",
        RU:   "results.txt очищен.",
        KZ_C: "results.txt тазартылды.",
        KZ_L: "results.txt tazartyldy.",
    },
    "clear_already_empty": {
        EN:   "results.txt is already empty or does not exist.",
        RU:   "results.txt уже пуст или не существует.",
        KZ_C: "results.txt бос немесе жоқ.",
        KZ_L: "results.txt bos nemese joq.",
    },
    "results_saved": {
        EN:   "Results saved to results.txt",
        RU:   "Результаты сохранены в results.txt",
        KZ_C: "Нәтижелер results.txt-ке сақталды",
        KZ_L: "Nätijeler results.txt-ke saqtaldy",
    },
    "section_summary":    { EN: "Chat Overview",         RU: "Обзор чата",              KZ_C: "Чат шолу",              KZ_L: "Şat şolw"              },
    "section_users":      { EN: "Top Users",             RU: "Топ пользователей",       KZ_C: "Топ пайдаланушылар",    KZ_L: "Top paıdalanwşylar"    },
    "section_activity":   { EN: "Activity",              RU: "Активность",              KZ_C: "Белсенділік",           KZ_L: "Belsendіlіk"           },
    "section_graph":      { EN: "Interaction Graph",     RU: "Граф взаимодействий",     KZ_C: "Өзара әрекет графы",   KZ_L: "Özara äreqet grafy"    },
    "section_topics":     { EN: "Topics & Tech Stack",   RU: "Темы и стек технологий",  KZ_C: "Тақырыптар мен технологиялар", KZ_L: "Taqyrypttar men texnologıalar" },
    "section_media":      { EN: "Media Files",           RU: "Медиафайлы",              KZ_C: "Медиафайлдар",          KZ_L: "Medıafaıldar"          },
    "section_ghosts":     { EN: "Silent Members",        RU: "Молчуны",                 KZ_C: "Үнсіздер",             KZ_L: "Ünsizder"              },
    "section_penalties":  { EN: "Penalty Events",        RU: "Штрафные баллы",          KZ_C: "Айыппұл оқиғалары",    KZ_L: "Aıyppwl oqığaları"     },
    "section_digest":     { EN: "AI Digest",             RU: "AI-дайджест",             KZ_C: "AI дайджест",           KZ_L: "AI daıjest"            },
    "all_done": {
        EN:   "All analyses complete.",
        RU:   "Все анализы выполнены.",
        KZ_C: "Барлық талдаулар аяқталды.",
        KZ_L: "Barlıq taldawlar aıaqtaldy.",
    },
    "run_digest_hint": {
        EN:   "Run 'digest' with ANTHROPIC_API_KEY for the AI digest.",
        RU:   "Запусти 'digest' с ANTHROPIC_API_KEY для AI-дайджеста.",
        KZ_C: "AI дайджест үшін ANTHROPIC_API_KEY-мен 'digest' іске қос.",
        KZ_L: "AI daıjest üşin ANTHROPIC_API_KEY-men 'digest' iske qos.",
    },
    "col_rank":       { EN: "#",            RU: "#",               KZ_C: "#",             KZ_L: "#"           },
    "col_user":       { EN: "User",         RU: "Пользователь",    KZ_C: "Пайдаланушы",   KZ_L: "Paıdalanwşy" },
    "col_messages":   { EN: "Messages",     RU: "Сообщений",       KZ_C: "Хабарлар",      KZ_L: "Habarlar"    },
    "col_activity":   { EN: "Activity",     RU: "Активность",      KZ_C: "Белсенділік",   KZ_L: "Belsendіlіk" },
    "col_hour":       { EN: "Hour",         RU: "Час",             KZ_C: "Сағат",         KZ_L: "Sağat"       },
    "col_count":      { EN: "Count",        RU: "Кол-во",          KZ_C: "Саны",          KZ_L: "Sany"        },
    "col_day":        { EN: "Day",          RU: "День",            KZ_C: "Күн",           KZ_L: "Kün"         },
    "col_date":       { EN: "Date",         RU: "Дата",            KZ_C: "Күні",          KZ_L: "Küni"        },
    "col_replied":    { EN: "From",         RU: "От кого",         KZ_C: "Кімнен",        KZ_L: "Kimnen"      },
    "col_to":         { EN: "To",           RU: "Кому",            KZ_C: "Кімге",         KZ_L: "Kimge"       },
    "col_times":      { EN: "Times",        RU: "Раз",             KZ_C: "Рет",           KZ_L: "Ret"         },
    "col_strength":   { EN: "Strength",     RU: "Сила",            KZ_C: "Күш",           KZ_L: "Küş"         },
    "col_tag":        { EN: "Tag",          RU: "Тег",             KZ_C: "Тег",           KZ_L: "Teg"         },
    "col_share":      { EN: "Share",        RU: "Доля",            KZ_C: "Үлес",          KZ_L: "Ülес"        },
    "col_dist":       { EN: "Distribution", RU: "Распределение",   KZ_C: "Таралуы",       KZ_L: "Taralwy"     },
    "col_tech":       { EN: "Technology",   RU: "Технология",      KZ_C: "Технология",    KZ_L: "Texnologıa"  },
    "col_mentions":   { EN: "Mentions",     RU: "Упоминаний",      KZ_C: "Аталым",        KZ_L: "Atalym"      },
    "col_popularity": { EN: "Popularity",   RU: "Популярность",    KZ_C: "Танымалдылық",  KZ_L: "Tanymaldy"   },
    "col_time":       { EN: "Time",         RU: "Время",           KZ_C: "Уақыт",         KZ_L: "Waqyt"       },
    "col_issuer":     { EN: "Issuer",       RU: "Кто выдал",       KZ_C: "Берген",        KZ_L: "Bergen"      },
    "col_points":     { EN: "Points",       RU: "Баллы",           KZ_C: "Ұпайлар",       KZ_L: "Wpaylar"     },
    "col_message":    { EN: "Message",      RU: "Сообщение",       KZ_C: "Хабар",         KZ_L: "Habar"       },
    "col_identifier": { EN: "Identifier",   RU: "Идентификатор",   KZ_C: "Идентификатор", KZ_L: "Identifikator" },
    "title_top_users": {
        EN:   "Top Users",
        RU:   "Топ пользователей",
        KZ_C: "Топ пайдаланушылар",
        KZ_L: "Top paıdalanwşylar",
    },
    "title_hourly": {
        EN:   "Activity by Hour",
        RU:   "Активность по часам",
        KZ_C: "Сағат бойынша белсенділік",
        KZ_L: "Sağat boınşa belsendіlіk",
    },
    "title_weekday": {
        EN:   "Activity by Day of Week",
        RU:   "Активность по дням недели",
        KZ_C: "Апта күндері бойынша белсенділік",
        KZ_L: "Apta künderi boınşa belsendіlіk",
    },
    "title_daily": {
        EN:   "Activity by Date",
        RU:   "Активность по датам",
        KZ_C: "Күндер бойынша белсенділік",
        KZ_L: "Künderi boınşa belsendіlіk",
    },
    "title_interactions": {
        EN:   "Top {n} Interactions",
        RU:   "Топ {n} взаимодействий",
        KZ_C: "Топ {n} өзара әрекет",
        KZ_L: "Top {n} özara äreqet",
    },
    "title_topics": {
        EN:   "Topic Distribution",
        RU:   "Распределение по темам",
        KZ_C: "Тақырыптар бойынша бөлу",
        KZ_L: "Taqyrypttar boınşa bölw",
    },
    "title_tech": {
        EN:   "Tech Stack Mentions",
        RU:   "Упоминания технологий",
        KZ_C: "Технологиялар аталымы",
        KZ_L: "Texnologıalar atalymy",
    },
    "title_media": {
        EN:   "Media Senders",
        RU:   "Отправители медиа",
        KZ_C: "Медиа жіберушілер",
        KZ_L: "Medıa jiberüşiler",
    },
    "title_ghosts": {
        EN:   "Silent Members ({n} total)",
        RU:   "Молчуны ({n} всего)",
        KZ_C: "Үнсіздер ({n} барлығы)",
        KZ_L: "Ünsizder ({n} barlığy)",
    },
    "title_penalties": {
        EN:   "Penalty / Bonus Events ({n} total)",
        RU:   "Штрафные / бонусные события ({n} всего)",
        KZ_C: "Айыппұл / бонус оқиғалары ({n} барлығы)",
        KZ_L: "Aıyppwl / bonws oqığaları ({n} barlığy)",
    },
    "summary_messages": {
        EN:   "Messages",
        RU:   "Сообщений",
        KZ_C: "Хабарлар",
        KZ_L: "Habarlar",
    },
    "summary_user": {
        EN:   "user",
        RU:   "пользовательских",
        KZ_C: "пайдаланушы",
        KZ_L: "paıdalanwşy",
    },
    "summary_system": {
        EN:   "system",
        RU:   "системных",
        KZ_C: "жүйелік",
        KZ_L: "jüıelik",
    },
    "summary_unique_users": {
        EN:   "Unique users",
        RU:   "Уникальных пользователей",
        KZ_C: "Бірегей пайдаланушылар",
        KZ_L: "Biregey paıdalanwşylar",
    },
    "summary_ghosts_note": {
        EN:   "joined, never wrote",
        RU:   "вошли, не написали",
        KZ_C: "қосылды, жазбады",
        KZ_L: "qosyldy, jazbady",
    },
    "summary_date_range": {
        EN:   "Date range",
        RU:   "Период",
        KZ_C: "Кезең",
        KZ_L: "Kezеn",
    },
    "summary_days": {
        EN:   "days",
        RU:   "дней",
        KZ_C: "күн",
        KZ_L: "kün",
    },
    "summary_avg_day": {
        EN:   "Avg per day",
        RU:   "Среднее в день",
        KZ_C: "Күніне орташа",
        KZ_L: "Küníne ortaşa",
    },
    "summary_peak_hour": {
        EN:   "Peak hour",
        RU:   "Пиковый час",
        KZ_C: "Шыңы сағат",
        KZ_L: "Şyny sağat",
    },
    "summary_active_day": {
        EN:   "Most active day",
        RU:   "Самый активный день",
        KZ_C: "Ең белсенді күн",
        KZ_L: "En belsendi kün",
    },
    "summary_media": {
        EN:   "Media files",
        RU:   "Медиафайлов",
        KZ_C: "Медиафайлдар",
        KZ_L: "Medıafaıldar",
    },
    "weekday_mon": { EN: "Mon", RU: "Пн", KZ_C: "Дс", KZ_L: "Ds" },
    "weekday_tue": { EN: "Tue", RU: "Вт", KZ_C: "Сс", KZ_L: "Ss" },
    "weekday_wed": { EN: "Wed", RU: "Ср", KZ_C: "Ср", KZ_L: "Sr" },
    "weekday_thu": { EN: "Thu", RU: "Чт", KZ_C: "Бс", KZ_L: "Bs" },
    "weekday_fri": { EN: "Fri", RU: "Пт", KZ_C: "Жм", KZ_L: "Jm" },
    "weekday_sat": { EN: "Sat", RU: "Сб", KZ_C: "Сн", KZ_L: "Sn" },
    "weekday_sun": { EN: "Sun", RU: "Вс", KZ_C: "Жс", KZ_L: "Js" },
    "time_night":     { EN: "00-05 Night",     RU: "00-05 Ночь",     KZ_C: "00-05 Түн",      KZ_L: "00-05 Tün"     },
    "time_morning":   { EN: "06-11 Morning",   RU: "06-11 Утро",     KZ_C: "06-11 Таң",      KZ_L: "06-11 Tan"     },
    "time_afternoon": { EN: "12-17 Afternoon", RU: "12-17 День",     KZ_C: "12-17 Күндіз",   KZ_L: "12-17 Kundiz"  },
    "time_evening":   { EN: "18-23 Evening",   RU: "18-23 Вечер",    KZ_C: "18-23 Кеш",      KZ_L: "18-23 Keş"     },
    "interaction_note": {
        EN:   "Interaction = reply within 2 min after previous message",
        RU:   "Взаимодействие = ответ в течение 2 мин после предыдущего сообщения",
        KZ_C: "Өзара әрекет = алдыңғы хабардан кейін 2 мин ішіндегі жауап",
        KZ_L: "Özara äreqet = aldınğy habardyn keyin 2 min işindegi jawap",
    },
    "no_data":        { EN: "No data.",                    RU: "Нет данных.",                 KZ_C: "Деректер жоқ.",           KZ_L: "Dereqter joq."          },
    "no_interactions":{ EN: "No interaction data.",        RU: "Нет данных о взаимодействиях.", KZ_C: "Өзара әрекет деректері жоқ.", KZ_L: "Özara äreqet dereqteri joq." },
    "no_ghosts":      { EN: "No silent members found.",    RU: "Молчунов не найдено.",        KZ_C: "Үнсіздер табылмады.",     KZ_L: "Ünsizder tabylmady."    },
    "no_penalties":   { EN: "No penalty events found.",    RU: "Штрафных событий не найдено.",KZ_C: "Айыппұл оқиғалары жоқ.", KZ_L: "Aıyppwl oqığaları joq." },
    "no_media":       { EN: "No media attachments found.", RU: "Медиафайлов не найдено.",     KZ_C: "Медиафайлдар жоқ.",       KZ_L: "Medıafaıldar joq."      },
    "no_tech":        { EN: "No tech mentions found.",     RU: "Упоминаний технологий не найдено.", KZ_C: "Технологиялар аталымы жоқ.", KZ_L: "Texnologıalar atalymy joq." },
    "no_topics":      { EN: "No topic data.",              RU: "Данных по темам нет.",        KZ_C: "Тақырып деректері жоқ.",  KZ_L: "Taqyrypt dereqteri joq." },
    "digest_no_key": {
        EN:   "ANTHROPIC_API_KEY is not set.\nExport it with: export ANTHROPIC_API_KEY=sk-ant-...",
        RU:   "ANTHROPIC_API_KEY не задан.\nУстанови: export ANTHROPIC_API_KEY=sk-ant-...",
        KZ_C: "ANTHROPIC_API_KEY орнатылмаған.\nОрнат: export ANTHROPIC_API_KEY=sk-ant-...",
        KZ_L: "ANTHROPIC_API_KEY ornатылmağan.\nOrnat: export ANTHROPIC_API_KEY=sk-ant-...",
    },
    "digest_generating": {
        EN:   "Generating AI digest for {n} day(s)...",
        RU:   "Генерирую AI-дайджест для {n} дня(ей)...",
        KZ_C: "{n} күн(дер) үшін AI дайджест жасалуда...",
        KZ_L: "{n} kün(der) üşin AI daıjest jasalwda...",
    },
    "digest_processing": {
        EN:   "Processing {date} ({n} messages)...",
        RU:   "Обрабатываю {date} ({n} сообщений)...",
        KZ_C: "{date} өңделуде ({n} хабар)...",
        KZ_L: "{date} öndelwde ({n} habar)...",
    },
    "digest_done": {
        EN:   "Done",
        RU:   "Готово",
        KZ_C: "Дайын",
        KZ_L: "Daıyn",
    },
    "digest_error": {
        EN:   "Error",
        RU:   "Ошибка",
        KZ_C: "Қате",
        KZ_L: "Qate",
    },
    "digest_skipping": {
        EN:   "Skipping {date}",
        RU:   "Пропускаю {date}",
        KZ_C: "{date} өткізіп жіберу",
        KZ_L: "{date} ötkizip jiberw",
    },
    "digest_no_messages": {
        EN:   "No messages found for the selected date(s).",
        RU:   "Сообщений для выбранных дат не найдено.",
        KZ_C: "Таңдалған күндер үшін хабарлар жоқ.",
        KZ_L: "Tandалğan künder üşin habarlar joq.",
    },
    "digest_date_prompt": {
        EN:   "Date for digest (YYYY-MM-DD, or Enter for all dates)",
        RU:   "Дата для дайджеста (YYYY-MM-DD, или Enter для всех дат)",
        KZ_C: "Дайджест күні (YYYY-MM-DD, немесе барлық күндер үшін Enter)",
        KZ_L: "Daıjest küni (YYYY-MM-DD, nemese barlıq künder üşin Enter)",
    },
    "digest_bad_date": {
        EN:   "Invalid date format. Use YYYY-MM-DD",
        RU:   "Неверный формат даты. Используй YYYY-MM-DD",
        KZ_C: "Қате күн пішімі. YYYY-MM-DD пайдалан",
        KZ_L: "Qate kün pişimi. YYYY-MM-DD paıdalan",
    },
    "digest_mood_energetic": { EN: "Energetic", RU: "Энергичный", KZ_C: "Жігерлі",   KZ_L: "Jigerli"   },
    "digest_mood_focused":   { EN: "Focused",   RU: "Сосредоточенный", KZ_C: "Шоғырланған", KZ_L: "Şoğyrlanğan" },
    "digest_mood_tense":     { EN: "Tense",     RU: "Напряжённый", KZ_C: "Шиеленіскен", KZ_L: "Şielenisken" },
    "digest_mood_relaxed":   { EN: "Relaxed",   RU: "Расслабленный", KZ_C: "Тыныш",   KZ_L: "Tynyş"     },
    "digest_mood_chaotic":   { EN: "Chaotic",   RU: "Хаотичный",   KZ_C: "Хаостық",   KZ_L: "Xaostıq"   },
    "digest_messages_count": { EN: "messages",  RU: "сообщений",   KZ_C: "хабар",      KZ_L: "habar"     },
    "digest_mood_label":     { EN: "Mood",      RU: "Настроение",  KZ_C: "Көңіл-күй", KZ_L: "Könil-küı" },
    "digest_topics_label":   { EN: "Top topics", RU: "Главные темы", KZ_C: "Негізгі тақырыптар", KZ_L: "Negizgi taqyrypttar" },
    "digest_moments_label":  { EN: "Key moments", RU: "Ключевые моменты", KZ_C: "Негізгі сәттер", KZ_L: "Negizgi sätter" },
    "digest_helpful_label":  { EN: "Most helpful", RU: "Самые полезные", KZ_C: "Ең пайдалы", KZ_L: "En paıdaly" },
    "digest_summary_label":  { EN: "Summary",   RU: "Итог",        KZ_C: "Қорытынды",  KZ_L: "Qorytyndy" },
    "cli_summary":   { EN: "Chat overview.",          RU: "Обзор чата.",             KZ_C: "Чат шолу.",             KZ_L: "Şat şolw."             },
    "cli_users":     { EN: "Top users.",              RU: "Топ пользователей.",      KZ_C: "Топ пайдаланушылар.",   KZ_L: "Top paıdalanwşylar."   },
    "cli_activity":  { EN: "Activity over time.",     RU: "Активность по времени.",  KZ_C: "Уақыт бойынша белсенділік.", KZ_L: "Waqyt boınşa belsendіlіk." },
    "cli_graph":     { EN: "Interaction graph.",      RU: "Граф взаимодействий.",    KZ_C: "Өзара әрекет графы.",  KZ_L: "Özara äreqet grafy."   },
    "cli_topics":    { EN: "Topics & tech stack.",    RU: "Темы и технологии.",      KZ_C: "Тақырыптар мен технологиялар.", KZ_L: "Taqyrypttar men texnologıalar." },
    "cli_media":     { EN: "Media files.",            RU: "Медиафайлы.",             KZ_C: "Медиафайлдар.",         KZ_L: "Medıafaıldar."         },
    "cli_ghosts":    { EN: "Silent members.",         RU: "Молчуны.",                KZ_C: "Үнсіздер.",            KZ_L: "Ünsizder."             },
    "cli_penalties": { EN: "Penalty events.",         RU: "Штрафные баллы.",         KZ_C: "Айыппұл оқиғалары.",   KZ_L: "Aıyppwl oqığaları."    },
    "cli_digest":    { EN: "AI digest. Requires ANTHROPIC_API_KEY.", RU: "AI-дайджест. Требует ANTHROPIC_API_KEY.", KZ_C: "AI дайджест. ANTHROPIC_API_KEY қажет.", KZ_L: "AI daıjest. ANTHROPIC_API_KEY qajet." },
    "cli_all":       { EN: "Run all analyses.",       RU: "Запустить все анализы.",  KZ_C: "Барлық талдауларды іске қос.", KZ_L: "Barlıq taldawlardy iske qos." },
    "cli_clear":     { EN: "Clear results.txt.",      RU: "Очистить results.txt.",   KZ_C: "results.txt тазарту.", KZ_L: "results.txt tazartw."  },
    "cli_menu":      { EN: "Interactive menu (recommended).", RU: "Интерактивное меню (рекомендуется).", KZ_C: "Интерактивті мәзір (ұсынылады).", KZ_L: "Interaktıvti mäzir (wsunylady)." },
    "cli_app":       { EN: "WhatsApp chat analytics tool.", RU: "Инструмент аналитики чатов WhatsApp.", KZ_C: "WhatsApp чат аналитика құралы.", KZ_L: "WhatsApp şat analıtıka qwraly." },
}
class Translator:
    def __init__(self, lang: str = EN):
        self._lang = lang
    @property
    def lang(self) -> str:
        return self._lang
    def set_lang(self, lang: str) -> None:
        self._lang = lang
    def __call__(self, key: str, **kwargs) -> str:
        """Translate key to current language, with optional format kwargs."""
        table = _STRINGS.get(key)
        if table is None:
            return key
        text = table.get(self._lang) or table.get(EN, key)
        if kwargs:
            try:
                text = text.format(**kwargs)
            except KeyError:
                pass
        return text
    def weekday_names(self) -> list[str]:
        keys = ["weekday_mon", "weekday_tue", "weekday_wed", "weekday_thu",
                "weekday_fri", "weekday_sat", "weekday_sun"]
        return [self(k) for k in keys]
T = Translator(EN)
